import axios from 'axios';
const key = process.env.REACT_APP_WEATHER_API_KEY;

export const getAllCities = addCity => {
  axios.get(`/forecast/${key}/40.6635,-73.9387?exclude=minutely,hourly`)
    .then(city => addCity('new_york', city.data))
  axios.get(`/forecast/${key}/41.8376,-87.6818?exclude=minutely,hourly`)
    .then(city => addCity('chicago', city.data))
  axios.get(`/forecast/${key}/34.0194,-118.4108?exclude=minutely,hourly`)
    .then(city => addCity('los_angles', city.data))
  axios.get(`/forecast/${key}/29.7866,-95.3909?exclude=minutely,hourly`)
    .then(city => addCity('houston', city.data))
  axios.get(`/forecast/${key}/33.5722,-112.0901?exclude=minutely,hourly`)
    .then(city => addCity('phoenix', city.data))
  axios.get(`/forecast/${key}/40.0094,-75.1333?exclude=minutely,hourly`)
    .then(city => addCity('philadelphia', city.data))
  axios.get(`/forecast/${key}/29.4724,-98.5251?exclude=minutely,hourly`)
    .then(city => addCity('san_antonio', city.data))
  axios.get(`/forecast/${key}/32.8153,-117.1350?exclude=minutely,hourly`)
    .then(city => addCity('san_diego', city.data))
  axios.get(`/forecast/${key}/32.7933,-96.7665?exclude=minutely,hourly`)
    .then(city => addCity('dallas', city.data))
  axios.get(`/forecast/${key}/37.2967,-121.8189?exclude=minutely,hourly`)
    .then(city => addCity('san_jose', city.data))
  axios.get(`/forecast/${key}/30.3039,-97.7544?exclude=minutely,hourly`)
    .then(city => addCity('austin', city.data))
  axios.get(`/forecast/${key}/30.3369,-81.6616?exclude=minutely,hourly`)
    .then(city => addCity('jacksonville', city.data))
  axios.get(`/forecast/${key}/37.7272,-123.0322?exclude=minutely,hourly`)
    .then(city => addCity('san_francisco', city.data))
  axios.get(`/forecast/${key}/39.9852,-82.9848?exclude=minutely,hourly`)
    .then(city => addCity('columbus', city.data))
  axios.get(`/forecast/${key}/32.7815,-97.3467?exclude=minutely,hourly`)
    .then(city => addCity('fort_worth', city.data))
  axios.get(`/forecast/${key}/39.7767,-86.1459?exclude=minutely,hourly`)
    .then(city => addCity('indianapolis', city.data))
  axios.get(`/forecast/${key}/35.2078,-80.8310?exclude=minutely,hourly`)
    .then(city => addCity('charlotte', city.data))
  axios.get(`/forecast/${key}/47.6205,-122.3509?exclude=minutely,hourly`)
    .then(city => addCity('seattle', city.data))
  axios.get(`/forecast/${key}/39.7619,-104.8811?exclude=minutely,hourly`)
    .then(city => addCity('denver', city.data))
  axios.get(`/forecast/${key}/38.9041,-77.0172?exclude=minutely,hourly`)
    .then(city => addCity('washington', city.data))
  axios.get(`/forecast/${key}/42.3320,-71.0202?exclude=minutely,hourly`)
    .then(city => addCity('boston', city.data))
}
